### ISSUE TITLE
デザイン

### ISSUE THREAD

**Issue by candy12t** [jphacks/F_2010#1]

**Comment by Yui-Sgt** [comment]
わ〜〜〜

**Comment by Yui-Sgt** [comment]
作って見たよ

**Comment by Yui-Sgt** [comment]
https://www.figma.com/file/0xbeWss6X4ilkkWcO0rc77/%E8%87%AA%E6%AE%BA%E9%98%B2%E6%AD%A2?node-id=0%3A1

figma でプロトタイプ 作りました〜！あんま機能詰めれてないな〜と言うのはみんなわかっていると思うので、このAppのユーザーストーリーマップ考えてますね〜
